---
- name: Simple playbook    # describes the playbook
  hosts: planetexpress     # this is a reference to a group or host in the inventory
  connection: ssh          # default type

  tasks:
  - name: "apt module - Install a simple application"
    apt:
      name: figlet
      state: present
    become: true  # elevates an ansible module to
                  # "sudo" (linux), "admin" (windows), "enable" (many switches), etc.
                  
  - name: "copy module - copy a file to our server"
    ansible.builtin.copy:
      src: ~/pyansDB/files/sample.cfg   # on the controller
      dest: ~/sample.cfg                # location on servers

