---
- name: Playbook for working with MongoDB
  hosts: localhost
  connection: local
  gather_facts: false


  tasks:
          - name: Call on our Python3 Mongo Script
            script: /home/student/pyansDB/pyMongo01.py
            args:
                executable: python3
            register: results

          - name: Display the results of our script
            debug:
                    var: results

          - name: Display std result of our script
            debug:
                    var: results.stdout_lines

          - name: pretty print what came back
            debug:
                    var: results.stdout | to_nice_json

          - name: just the keys
            debug:
                    var: results.keys()

          - name: copy out the results
            copy:
                    content: "{{ results.stdout }}"
                    dest: /home/student/geteyeballsondata
